# generated by Neptune Namespaces
# file: stepDone/models/namespace.coffee

StepDone = require '../namespace'
module.exports = StepDone.Models ||
class StepDone.Models extends Neptune.Base
  @namespace: StepDone
  @namespacePath: "Neptune.StepDone.Models"

StepDone.addNamespace StepDone.Models