# generated by Neptune Namespaces v1.x.x
# file: step05_with_aws/Pipelines/namespace.coffee

Step05WithAws = require '../namespace'
module.exports = Step05WithAws.Pipelines ||
Step05WithAws.addNamespace 'Pipelines', class Pipelines extends Neptune.Base
  ;