// generated by Neptune Namespaces v4.x.x
// file: step01/namespace.js

module.exports = require('neptune-namespaces').addNamespace(
  'Step01',
  (class Step01 extends Neptune.PackageNamespace {})
  ._configureNamespace(require('../../package.json'))
);
