# generated by Neptune Namespaces v3.x.x
# file: step01/namespace.coffee

module.exports = (require 'neptune-namespaces').addNamespace 'Step01', class Step01 extends Neptune.PackageNamespace
  @version: require('../../package.json').version
