# generated by Neptune Namespaces v0.5
# file: step05_with_aws/Components/index.coffee

module.exports = require './namespace'
.addModules
  App:         require './App'        
  ChatMessage: require './ChatMessage'
  ChatView:    require './ChatView'   