// generated by Neptune Namespaces v4.x.x
// file: step05/Components/index.js

(module.exports = require('./namespace'))

.addModules({
  App:         require('./App'),
  Button:      require('./Button'),
  ChatMessage: require('./ChatMessage'),
  ChatView:    require('./ChatView'),
  Lobby:       require('./Lobby')
});