# generated by Neptune Namespaces v1.x.x
# file: step05/Components/index.coffee

module.exports = require './namespace'
.addModules
  App:         require './App'        
  ChatMessage: require './ChatMessage'
  ChatView:    require './ChatView'   