# generated by Neptune Namespaces v1.x.x
# file: step05/Components/namespace.coffee

Step05 = require '../namespace'
module.exports = Step05.Components ||
Step05.addNamespace 'Components', class Components extends Neptune.Base
  ;