# generated by Neptune Namespaces
# file: step05/index.coffee

module.exports =
Step05             = require './namespace'
Step05.App         = require './app'
Step05.ChatMessage = require './chat_message'
Step05.ChatModel   = require './chat_model'
Step05.ChatView    = require './chat_view'
Step05.Config      = require './config'
Step05.Main        = require './main'
Step05.StyleProps  = require './style_props'
Step05.finishLoad(
  ["App","ChatMessage","ChatModel","ChatView","Config","Main","StyleProps"]
)