# generated by Neptune Namespaces
# file: step05/index.coffee

(module.exports = require './namespace')
.addModules
  App:         require './app'
  ChatMessage: require './chat_message'
  ChatModel:   require './chat_model'
  ChatView:    require './chat_view'
  Config:      require './config'
  Main:        require './main'
  StyleProps:  require './style_props'
