# generated by Neptune Namespaces v0.3.0
# file: step05/namespace.coffee

require 'neptune-namespaces'
module.exports = Neptune.Step05 ||
Neptune.addNamespace 'Step05', class Step05 extends Neptune.Base
  ;