# generated by Neptune Namespaces v1.x.x
# file: step05/namespace.coffee

Neptune = require 'neptune-namespaces'
module.exports = Neptune.Step05 ||
Neptune.addNamespace 'Step05', class Step05 extends Neptune.Base
  ;