# generated by Neptune Namespaces v3.x.x
# file: step06/Components/index.coffee

module.exports = require './namespace'
module.exports
.addModules
  App:         require './App'        
  ChatMessage: require './ChatMessage'
  ChatView:    require './ChatView'   