// generated by Neptune Namespaces v4.x.x
// file: step06/Components/index.js

(module.exports = require('./namespace'))

.addModules({
  App:         require('./App'),
  ChatMessage: require('./ChatMessage'),
  ChatView:    require('./ChatView')
});