// generated by Neptune Namespaces v4.x.x
// file: step05/index.js

(module.exports = require('./namespace'))

.addModules({
  Main:       require('./Main'),
  Palette:    require('./Palette'),
  StyleProps: require('./StyleProps')
});
require('./Components');
require('./Configs');
require('./Pipelines');