# generated by Neptune Namespaces v2.x.x
# file: step05/index.coffee

module.exports = require './namespace'
module.exports
.addModules
  Main:       require './Main'      
  StyleProps: require './StyleProps'
require './Components'
require './Configs'
require './Pipelines'