// generated by Neptune Namespaces v4.x.x
// file: step05/namespace.js

module.exports = require('neptune-namespaces').addNamespace(
  'Step05',
  (class Step05 extends Neptune.PackageNamespace {})
  ._configureNamespace(require('../../package.json'))
);
require('./Components/namespace');
require('./Configs/namespace');
require('./Pipelines/namespace');