# generated by Neptune Namespaces v3.x.x
# file: step06/Pipelines/namespace.coffee

module.exports = (require '../namespace').addNamespace('Pipelines', class Pipelines extends Neptune.PackageNamespace)
