// generated by Neptune Namespaces v4.x.x
// file: step06/Configs/namespace.js

module.exports = require('../namespace').addNamespace(
  'Configs',
  class Configs extends Neptune.PackageNamespace {}
);
