# generated by Neptune Namespaces v0.6
# file: step03/index.coffee

module.exports = require './namespace'
.addModules
  App:         require './app'         
  ChatMessage: require './chat_message'
  ChatView:    require './chat_view'   
  Main:        require './main'        
  StyleProps:  require './style_props' 