# generated by Neptune Namespaces
# file: step03/index.coffee

module.exports =
Step03             = require './namespace'
Step03.App         = require './app'
Step03.ChatMessage = require './chat_message'
Step03.ChatView    = require './chat_view'
Step03.Main        = require './main'
Step03.StyleProps  = require './style_props'
Step03.finishLoad(
  ["App","ChatMessage","ChatView","Main","StyleProps"]
)