# generated by Neptune Namespaces
# file: step03/namespace.coffee

require 'neptune-namespaces'
module.exports = Neptune.Step03 ||
class Neptune.Step03 extends Neptune.Base
  @namespace: Neptune
  @namespacePath: "Neptune.Step03"

Neptune.addNamespace Neptune.Step03