# generated by Neptune Namespaces v0.3.0
# file: step03/namespace.coffee

require 'neptune-namespaces'
module.exports = Neptune.Step03 ||
Neptune.addNamespace 'Step03', class Step03 extends Neptune.Base
  ;