# generated by Neptune Namespaces v1.x.x
# file: step01/namespace.coffee

Neptune = require 'neptune-namespaces'
module.exports = Neptune.Step01 ||
Neptune.addNamespace 'Step01', class Step01 extends Neptune.Base
  ;