# generated by Neptune Namespaces v1.x.x
# file: step05_with_aws/Components/namespace.coffee

Step05WithAws = require '../namespace'
module.exports = Step05WithAws.Components ||
Step05WithAws.addNamespace 'Components', class Components extends Neptune.Base
  ;