# generated by Neptune Namespaces
# file: step02/index.coffee

module.exports =
Step02          = require './namespace'
Step02.App      = require './app'
Step02.ChatView = require './chat_view'
Step02.Main     = require './main'
Step02.finishLoad(
  ["App","ChatView","Main"]
)