# generated by Neptune Namespaces
# file: step02/index.coffee

(module.exports = require './namespace')
.addModules
  App:      require './app'
  ChatView: require './chat_view'
  Main:     require './main'
