# generated by Neptune Namespaces v0.4.1
# file: step02/namespace.coffee

require 'neptune-namespaces'
module.exports = Neptune.Step02 ||
Neptune.addNamespace 'Step02', class Step02 extends Neptune.Base
  ;