# generated by Neptune Namespaces
# file: step90_local_chat/index.coffee

module.exports =
Step90LocalChat             = require './namespace'
Step90LocalChat.App         = require './app'
Step90LocalChat.ChatMessage = require './chat_message'
Step90LocalChat.ChatModel   = require './chat_model'
Step90LocalChat.ChatView    = require './chat_view'
Step90LocalChat.Main        = require './main'
Step90LocalChat.StyleProps  = require './style_props'
Step90LocalChat.finishLoad(
  ["App","ChatMessage","ChatModel","ChatView","Main","StyleProps"]
)