# generated by Neptune Namespaces
# file: step90_local_chat/namespace.coffee

require 'neptune-namespaces'
module.exports = Neptune.Step90LocalChat ||
class Neptune.Step90LocalChat extends Neptune.Base
  @namespace: Neptune
  @namespacePath: "Neptune.Step90LocalChat"

Neptune.addNamespace Neptune.Step90LocalChat