# generated by Neptune Namespaces v3.x.x
# file: step04/index.coffee

module.exports = require './namespace'
module.exports
.addModules
  App:         require './App'        
  ChatMessage: require './ChatMessage'
  ChatModel:   require './ChatModel'  
  ChatView:    require './ChatView'   
  Main:        require './Main'       
  Palette:     require './Palette'    
  StyleProps:  require './StyleProps' 