// generated by Neptune Namespaces v4.x.x
// file: step04/index.js

(module.exports = require('./namespace'))

.addModules({
  App:         require('./App'),
  ChatMessage: require('./ChatMessage'),
  ChatModel:   require('./ChatModel'),
  ChatView:    require('./ChatView'),
  Main:        require('./Main'),
  Palette:     require('./Palette'),
  StyleProps:  require('./StyleProps')
});