# generated by Neptune Namespaces v3.x.x
# file: step04/namespace.coffee

module.exports = (require 'neptune-namespaces').addNamespace 'Step04', class Step04 extends Neptune.PackageNamespace
  @version: require('../../package.json').version
