// generated by Neptune Namespaces v4.x.x
// file: step04/namespace.js

module.exports = require('neptune-namespaces').addNamespace(
  'Step04',
  (class Step04 extends Neptune.PackageNamespace {})
  ._configureNamespace(require('../../package.json'))
);
