# generated by Neptune Namespaces
# file: step_done/components/index.coffee

module.exports =
Components          = require './namespace'
Components.ChatView = require './chat_view'
Components.finishLoad(
  ["ChatView"]
)