# generated by Neptune Namespaces
# file: stepDone/components/namespace.coffee

StepDone = require '../namespace'
module.exports = StepDone.Components ||
class StepDone.Components extends Neptune.Base
  @namespace: StepDone
  @namespacePath: "Neptune.StepDone.Components"

StepDone.addNamespace StepDone.Components