# generated by Neptune Namespaces v0.5
# file: step06/index.coffee

require './-requires'
module.exports = require './namespace'
.addModules
  App:         require './App'        
  ChatMessage: require './ChatMessage'
  ChatView:    require './ChatView'   
  Config:      require './Config'     
  Main:        require './Main'       
  StyleProps:  require './StyleProps' 
require './Models'