# generated by Neptune Namespaces v0.5
# file: step06/namespace.coffee

Neptune = require 'neptune-namespaces'
module.exports = Neptune.Step06 ||
Neptune.addNamespace 'Step06', class Step06 extends Neptune.Base
  ;