# generated by Neptune Namespaces v0.5
# file: step04/index.coffee

module.exports = require './namespace'
.addModules
  App:         require './app'         
  ChatMessage: require './chat_message'
  ChatModel:   require './chat_model'  
  ChatView:    require './chat_view'   
  Main:        require './main'        
  StyleProps:  require './style_props' 