# generated by Neptune Namespaces
# file: step04/index.coffee

module.exports =
Step04             = require './namespace'
Step04.App         = require './app'
Step04.ChatMessage = require './chat_message'
Step04.ChatModel   = require './chat_model'
Step04.ChatView    = require './chat_view'
Step04.Main        = require './main'
Step04.StyleProps  = require './style_props'
Step04.finishLoad(
  ["App","ChatMessage","ChatModel","ChatView","Main","StyleProps"]
)