# generated by Neptune Namespaces v0.4.1
# file: step04/namespace.coffee

require 'neptune-namespaces'
module.exports = Neptune.Step04 ||
Neptune.addNamespace 'Step04', class Step04 extends Neptune.Base
  ;