# generated by Neptune Namespaces v0.4.1
# file: step01/namespace.coffee

require 'neptune-namespaces'
module.exports = Neptune.Step01 ||
Neptune.addNamespace 'Step01', class Step01 extends Neptune.Base
  ;