# generated by Neptune Namespaces v0.6
# file: step01/namespace.coffee

Neptune = require 'neptune-namespaces'
module.exports = Neptune.Step01 ||
Neptune.addNamespace 'Step01', class Step01 extends Neptune.Base
  ;