# generated by Neptune Namespaces v2.x.x
# file: step05/Configs/namespace.coffee

Step05 = require '../namespace'
module.exports = Step05.Configs ||
Step05.addNamespace 'Configs', class Configs extends Neptune.Base
  ;
