# generated by Neptune Namespaces v0.6
# file: step05_with_aws/Config/namespace.coffee

Step05WithAws = require '../namespace'
module.exports = Step05WithAws.Config ||
Step05WithAws.addNamespace 'Config', class Config extends Neptune.Base
  ;