# generated by Neptune Namespaces
# file: step99_remote_chat/index.coffee

module.exports =
Step99RemoteChat             = require './namespace'
Step99RemoteChat.App         = require './app'
Step99RemoteChat.ChatMessage = require './chat_message'
Step99RemoteChat.ChatModel   = require './chat_model'
Step99RemoteChat.ChatView    = require './chat_view'
Step99RemoteChat.Config      = require './config'
Step99RemoteChat.Main        = require './main'
Step99RemoteChat.StyleProps  = require './style_props'
Step99RemoteChat.finishLoad(
  ["App","ChatMessage","ChatModel","ChatView","Config","Main","StyleProps"]
)