# generated by Neptune Namespaces
# file: step99_remote_chat/namespace.coffee

require 'neptune-namespaces'
module.exports = Neptune.Step99RemoteChat ||
class Neptune.Step99RemoteChat extends Neptune.Base
  @namespace: Neptune
  @namespacePath: "Neptune.Step99RemoteChat"

Neptune.addNamespace Neptune.Step99RemoteChat