# generated by Neptune Namespaces v2.x.x
# file: step05/Pipelines/namespace.coffee

Step05 = require '../namespace'
module.exports = Step05.Pipelines ||
Step05.addNamespace 'Pipelines', class Pipelines extends Neptune.Base
  ;
