# generated by Neptune Namespaces v0.5
# file: step05_with_aws/Models/index.coffee

module.exports = require './namespace'
.addModules
  ArtEryFluxModel: require './ArtEryFluxModel'
  Chat:            require './Chat'           