# generated by Neptune Namespaces v0.5
# file: step05_with_aws/Models/namespace.coffee

Step05WithAws = require '../namespace'
module.exports = Step05WithAws.Models ||
Step05WithAws.addNamespace 'Models', class Models extends Neptune.Base
  ;