# generated by Neptune Namespaces v0.5
# file: step05_with_aws/index.coffee

require './-requires'
module.exports = require './namespace'
.addModules
  App:         require './App'        
  ChatMessage: require './ChatMessage'
  ChatView:    require './ChatView'   
  Main:        require './Main'       
  StyleProps:  require './StyleProps' 
require './Config'
require './Models'