# generated by Neptune Namespaces v0.5
# file: step05_with_aws/index.coffee

require './-requires'
module.exports = require './namespace'
.addModules
  Main:       require './Main'      
  StyleProps: require './StyleProps'
require './Components'
require './Config'
require './Models'