# generated by Neptune Namespaces v0.6
# file: step05_with_aws/namespace.coffee

Neptune = require 'neptune-namespaces'
module.exports = Neptune.Step05WithAws ||
Neptune.addNamespace 'Step05WithAws', class Step05WithAws extends Neptune.Base
  ;