# generated by Neptune Namespaces v1.x.x
# file: step04/namespace.coffee

Neptune = require 'neptune-namespaces'
module.exports = Neptune.Step04 ||
Neptune.addNamespace 'Step04', class Step04 extends Neptune.Base
  ;