# generated by Neptune Namespaces
# file: stepDone/namespace.coffee

require 'neptune-namespaces'
module.exports = Neptune.StepDone ||
class Neptune.StepDone extends Neptune.Base
  @namespace: Neptune
  @namespacePath: "Neptune.StepDone"

Neptune.addNamespace Neptune.StepDone