// generated by Neptune Namespaces v4.x.x
// file: step02/index.js

(module.exports = require('./namespace'))

.addModules({
  App:      require('./App'),
  ChatView: require('./ChatView'),
  Main:     require('./Main')
});