# generated by Neptune Namespaces v2.x.x
# file: step02/index.coffee

module.exports = require './namespace'
module.exports
.addModules
  App:      require './App'     
  ChatView: require './ChatView'
  Main:     require './Main'    