// generated by Neptune Namespaces v4.x.x
// file: step02/namespace.js

module.exports = require('neptune-namespaces').addNamespace(
  'Step02',
  (class Step02 extends Neptune.PackageNamespace {})
  ._configureNamespace(require('../../package.json'))
);
