# generated by Neptune Namespaces v3.x.x
# file: step02/namespace.coffee

module.exports = (require 'neptune-namespaces').addNamespace 'Step02', class Step02 extends Neptune.PackageNamespace
  @version: require('../../package.json').version
