# generated by Neptune Namespaces v2.x.x
# file: step03/index.coffee

module.exports = require './namespace'
module.exports
.addModules
  App:         require './App'        
  ChatMessage: require './ChatMessage'
  ChatView:    require './ChatView'   
  Main:        require './Main'       
  StyleProps:  require './StyleProps' 