# generated by Neptune Namespaces v3.x.x
# file: step03/namespace.coffee

module.exports = (require 'neptune-namespaces').addNamespace 'Step03', class Step03 extends Neptune.PackageNamespace
  @version: require('../../package.json').version
