# generated by Neptune Namespaces v2.x.x
# file: step03/namespace.coffee

Neptune = require 'neptune-namespaces'
module.exports = Neptune.Step03 ||
Neptune.addNamespace 'Step03', class Step03 extends Neptune.Base
  ;
