// generated by Neptune Namespaces v4.x.x
// file: step03/namespace.js

module.exports = require('neptune-namespaces').addNamespace(
  'Step03',
  (class Step03 extends Neptune.PackageNamespace {})
  ._configureNamespace(require('../../package.json'))
);
