# generated by Neptune Namespaces v0.5
# file: step06/Models/namespace.coffee

Step06 = require '../namespace'
module.exports = Step06.Models ||
Step06.addNamespace 'Models', class Models extends Neptune.Base
  ;