# generated by Neptune Namespaces v1.x.x
# file: step04/index.coffee

module.exports = require './namespace'
.addModules
  App:         require './App'        
  ChatMessage: require './ChatMessage'
  ChatModel:   require './ChatModel'  
  ChatView:    require './ChatView'   
  Main:        require './Main'       
  StyleProps:  require './StyleProps' 