// generated by Neptune Namespaces v4.x.x
// file: step06/namespace.js

module.exports = require('neptune-namespaces').addNamespace(
  'Step06',
  (class Step06 extends Neptune.PackageNamespace {})
  ._configureNamespace(require('../../package.json'))
);
require('./Components/namespace');
require('./Configs/namespace');
require('./Pipelines/namespace');