# generated by Neptune Namespaces v3.x.x
# file: step06/namespace.coffee

module.exports = (require 'neptune-namespaces').addNamespace 'Step06', class Step06 extends Neptune.PackageNamespace
  @version: require('../../package.json').version
require './Components/namespace';
require './Configs/namespace';
require './Pipelines/namespace'